import Head from 'next/head'
import { useState } from 'react'
import { Container, Input, Loading, Button, Text } from '@nextui-org/react'
import { Send, User, RefreshCcw } from 'lucide-react'
import { SigninModal, ThemeMode } from '@/components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex flex-col text-neutral-600">
        <section className="w-full h-16 flex items-center">
          <Header />
        </section>

        <section className="w-full md:mt-20">
          <MagicBoxWrapper />
        </section>
      </main>
    </>
  )
}

function Header() {
  const [open, setOpen] = useState(false)

  return (
    <Container display="flex" className="gap-2">
      <User className="cursor-pointer" onClick={() => setOpen(true)} />
      <ThemeMode />

      <SigninModal defaultAction="signin" open={open} onOpenChange={setOpen} />
    </Container>
  )
}

function MagicBoxWrapper() {
  const [loading, setLoading] = useState(false)

  return (
    <Container>
      <div className="flex items-center">
        <div className="md:w-1/3">
          <Input
            autoFocus
            underlined
            fullWidth
            color="primary"
            labelLeft={<Text b>ChatGPT</Text>}
            placeholder="Next UI"
          />
        </div>
        <Button auto light onClick={() => setLoading(!loading)}>
          {loading ? <Loading type="points" color="currentColor" size="sm" /> : <Send />}
        </Button>
        <Button auto light>
          <RefreshCcw />
        </Button>
      </div>
    </Container>
  )
}
